import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
// import { ToastContainer } from "react-toastify";
import CustomToaster from "@/components/ui/use-toast";
import logo from "@/public/Logo 1.png";
import Head from "next/head";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
const img = `<img src=${logo} />`;
export const metadata: Metadata = {
  title: "Maasta",
  description: "Generated by create next app",
  icons: "/Logo 1.png",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <>
      <SessionProvider session={session}>
        <html lang="en">
          <Head>
            <title>
              <img src="/Logo 1.png" />
            </title>
            <link rel="icon" href="/favicon.ico" />
            {/* Add other meta tags or link tags as needed */}
          </Head>

          <body
            className={cn(
              "min-h-screen bg-background font-sans antialiased",
              fontSans.variable
            )}
          >
            {children}
            <h1>hello file changed</h1>
            <CustomToaster />
          </body>
        </html>
      </SessionProvider>
    </>
  );
}
